import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sentence_transformers import SentenceTransformer, util
import os

# ==========================================
# CONFIGURATION
# ==========================================
class Config:
    # 1. INPUT FILES
    # The file generated by your previous script (containing N variations)
    RAW_AUGMENTED_FILE = "raw_augmented_stream_K3.csv" 
    
    # Original datasets (needed to fetch original text for comparison)
    REAL_DATASET_PATH = "LabeledAuthentic-7K.csv"
    FAKE_DATASET_PATH = "LabeledFake-1K.csv"

    # 2. SUBSAMPLING PARAMETERS
    K_SAMPLES = 2  # How many augmented samples to keep per original article (K <= N)
    
    # 3. OUTPUT FILES
    OUTPUT_SBERT = f"final_train_SBERT_K{K_SAMPLES}.csv"
    OUTPUT_RANDOM = f"final_train_RANDOM_K{K_SAMPLES}.csv"
    
    # Data Settings (Must match your previous script to ensure IDs align)
    TEST_SIZE = 0.3
    RANDOM_STATE = 50
    CONTENT_COLUMN = "content"
    LABEL_COLUMN = "label"
    CATEGORY_COLUMN = "category"

# ==========================================
# HELPER: RECONSTRUCT DATA SPLITS
# ==========================================
def reconstruct_training_data():
    """
    Re-loads and re-splits the data exactly as the previous script did
    to ensure we can look up the original text by ID.
    """
    print("--- Reconstructing Data Splits ---")
    df_real = pd.read_csv(Config.REAL_DATASET_PATH)
    df_fake = pd.read_csv(Config.FAKE_DATASET_PATH)
    
    # Ensure ID column exists
    df_fake['article_id'] = df_fake['articleID']
    
    # Split Real
    train_real, _ = train_test_split(
        df_real, test_size=Config.TEST_SIZE, 
        random_state=Config.RANDOM_STATE, stratify=df_real[Config.LABEL_COLUMN]
    )
    
    # Split Fake
    train_fake, _ = train_test_split(
        df_fake, test_size=Config.TEST_SIZE, 
        random_state=Config.RANDOM_STATE, stratify=df_fake[Config.LABEL_COLUMN]
    )
    
    print(f"Reconstructed Train Fake: {len(train_fake)} articles")
    return train_real, train_fake

# ==========================================
# STRATEGY 1: SBERT SIMILARITY SUBSAMPLING
# ==========================================
def perform_sbert_subsampling(train_fake_df, augmented_df, k):
    """
    Calculates Cosine Similarity between Original and Augmented.
    Selects Top K with highest similarity.
    """
    print(f"\n--- Running SBERT Subsampling (Top {k}) ---")
    
    # Load Model
    model = SentenceTransformer('all-MiniLM-L6-v2')
    
    selected_rows = []
    
    # Group augmented data by original article ID
    grouped = augmented_df.groupby('original_id')
    
    total_groups = len(grouped)
    for i, (orig_id, group) in enumerate(grouped):
        if i % 100 == 0:
            print(f"Processing group {i}/{total_groups}")
            
        # 1. Get Original Text
        try:
            orig_row = train_fake_df[train_fake_df['article_id'] == orig_id]
            if orig_row.empty:
                continue # Skip if original not found in split (should not happen if seed is same)
            
            original_text = orig_row[Config.CONTENT_COLUMN].iloc[0]
            
            # 2. Encode
            # Encode original
            emb_orig = model.encode(original_text, convert_to_tensor=True)
            
            # Encode candidates
            candidates = group[Config.CONTENT_COLUMN].tolist()
            emb_cand = model.encode(candidates, convert_to_tensor=True)
            
            # 3. Calculate Similarity
            # util.cos_sim returns a matrix, we want the first row
            scores = util.cos_sim(emb_orig, emb_cand)[0].cpu().numpy()
            
            # Assign scores to the group dataframe (avoiding SettingWithCopyWarning)
            group = group.copy()
            group['sbert_score'] = scores
            
            # 4. Sort and Select Top K
            top_k = group.sort_values(by='sbert_score', ascending=False).head(k)
            selected_rows.append(top_k)
            
        except Exception as e:
            print(f"Error processing {orig_id}: {e}")
            continue

    return pd.concat(selected_rows).reset_index(drop=True)

# ==========================================
# STRATEGY 2: RANDOM SUBSAMPLING
# ==========================================
def perform_random_subsampling(augmented_df, k):
    """
    Randomly selects K samples per original ID.
    """
    print(f"\n--- Running Random Subsampling (Random {k}) ---")
    
    selected_rows = []
    grouped = augmented_df.groupby('original_id')
    
    for orig_id, group in grouped:
        # If we have fewer generations than K, take all of them
        n_select = min(len(group), k)
        
        # Sample randomly
        random_k = group.sample(n=n_select, random_state=Config.RANDOM_STATE)
        selected_rows.append(random_k)
        
    return pd.concat(selected_rows).reset_index(drop=True)

# ==========================================
# DATA MERGING & EXPORT
# ==========================================
def build_final_dataset(train_real, train_fake_original, selected_augmented, filename):
    """
    Combines: Real Train + Fake Train (Original) + Fake Train (Selected Augmented)
    """
    print(f"Building dataset: {filename}")
    
    # 1. Prepare Original Fake (add flag)
    train_fake_original = train_fake_original.copy()
    train_fake_original['is_augmented'] = False
    train_fake_original['original_id'] = train_fake_original['article_id'] # Self reference
    
    # 2. Prepare Augmented Fake
    selected_augmented['is_augmented'] = True
    
    # 3. Combine Fake (Original + Augmented)
    # We concat them. Ordering isn't strictly necessary for training, 
    # but grouping by ID helps human readability.
    all_fake = pd.concat([
        train_fake_original[['article_id', 'original_id', Config.CONTENT_COLUMN, Config.LABEL_COLUMN, Config.CATEGORY_COLUMN, 'is_augmented']],
        selected_augmented[['article_id', 'original_id', Config.CONTENT_COLUMN, Config.LABEL_COLUMN, Config.CATEGORY_COLUMN, 'is_augmented']]
    ])
    
    # 4. Add Real Data
    train_real = train_real.copy()
    train_real['is_augmented'] = False
    train_real['original_id'] = train_real['articleID']
    train_real['article_id'] = train_real['articleID']
    
    final_df = pd.concat([
        train_real[['article_id', 'original_id', Config.CONTENT_COLUMN, Config.LABEL_COLUMN, Config.CATEGORY_COLUMN, 'is_augmented']],
        all_fake
    ])
    
    # Shuffle final dataset
    final_df = final_df.sample(frac=1, random_state=Config.RANDOM_STATE).reset_index(drop=True)
    
    # Save
    final_df.to_csv(filename, index=False)
    print(f"Saved {len(final_df)} rows to {filename}")
    print(f"Stats: {final_df['is_augmented'].value_counts().to_dict()} (False=Original, True=Augmented)")

# ==========================================
# MAIN EXECUTION
# ==========================================
if __name__ == "__main__":
    # 1. Load Data
    train_real, train_fake = reconstruct_training_data()
    
    if not os.path.exists(Config.RAW_AUGMENTED_FILE):
        print(f"ERROR: Could not find {Config.RAW_AUGMENTED_FILE}. Run the generation script first.")
        exit()
        
    raw_augmented_df = pd.read_csv(Config.RAW_AUGMENTED_FILE)
    print(f"Loaded {len(raw_augmented_df)} raw augmented samples.")

    # 2. Process SBERT Strategy
    sbert_selected = perform_sbert_subsampling(train_fake, raw_augmented_df, Config.K_SAMPLES)
    build_final_dataset(train_real, train_fake, sbert_selected, Config.OUTPUT_SBERT)

    # 3. Process Random Strategy
    random_selected = perform_random_subsampling(raw_augmented_df, Config.K_SAMPLES)
    build_final_dataset(train_real, train_fake, random_selected, Config.OUTPUT_RANDOM)
    
    print("\nProcessing Complete.")